version: '3.4'

services:

  persondb:
    image: mcr.microsoft.com/mssql/server:2017-latest

  rabbitmq:
    image: rabbitmq:3-management-alpine

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0

  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile

  elasticsearch:
    image: ${DOCKER_REGISTRY-}elasticsearch
    build:
      context: .
      dockerfile: Elasticsearch/Dockerfile
